# Generated by Django 6.1.1 on 2026-09-22 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_driver_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='driven_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
