# Generated by Django 6.1.1 on 2026-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_car_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
